In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(a.dtype, b.dtype)
print(a.shape, b.shape)
print(a.ndim, b.ndim)
print(a.itemsize, b.itemsize)
print(a.size, b.size)

[1 2 3]
[[1 2 3]
 [4 5 6]]
int32 int32
(3,) (2, 3)
1 2
4 4
3 6


In [3]:
print(np.zeros(10))
print(np.ones(10))
print(np.zeros([10,2]))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [4]:
print(np.identity(4))
print(np.eye(3,2))
print(np.logspace(3,4))
print(np.logspace(2,3,3))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]
[  1000.           1048.11313415   1098.54114199   1151.39539933
   1206.79264064   1264.85521686   1325.71136559   1389.49549437
   1456.3484775    1526.41796718   1599.85871961   1676.83293681
   1757.51062485   1842.06996933   1930.69772888   2023.58964773
   2120.95088792   2222.99648253   2329.95181052   2442.05309455
   2559.5479227    2682.69579528   2811.76869797   2947.05170255
   3088.84359648   3237.45754282   3393.2217719    3556.48030622
   3727.59372031   3906.93993705   4094.91506238   4291.93426013
   4498.43266897   4714.86636346   4941.71336132   5179.47467923
   5428.67543932   5689.86602902   5963.62331659   6250.55192527
   6551.2855686    6866.48845004   7196.85673001   7543.12006335
   7906.04321091   8286.42772855   8685.11373751   9102.98177992
   9540.9547635   10000.        ]
[  100.           316.22776602  1000.        ]


In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
np.linspace(1,4, 10) 

array([ 1.        ,  1.33333333,  1.66666667,  2.        ,  2.33333333,
        2.66666667,  3.        ,  3.33333333,  3.66666667,  4.        ])

In [7]:
np.tile([1,2], 5)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [8]:
a, b = np.meshgrid([1,2,3], [4,5,6,7,8])
a, b

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]]))

In [9]:
np.tri(10), np.diag(np.tri(10))

(array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]),
 array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]))

In [10]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
np.random.randint(0,100,10)

array([13, 76, 76, 40, 33, 38, 79, 27,  4, 43])

In [12]:
import sys
sys.version

'3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'

In [13]:
a = np.array([1,2,3,4])
print(a + 1)
print(a * 2)
print(a **2)
b = np.ones(4)
print(b)
print(a-b)
print(a * (b+1))
print(a ** (b+1))
c = np.ones((3,3))
print(c)
print(c*c)
print(c.dot(c)) # 行列積
print(a > b)
print(a==b)
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.array_equal(a,b))
print(a==b)
a = np.array([1, 1, 0, 0], dtype=bool)
print(a)

[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]
[ 1.  1.  1.  1.]
[ 0.  1.  2.  3.]
[ 2.  4.  6.  8.]
[  1.   4.   9.  16.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]
[False  True  True  True]
[ True False False False]
True
[ True  True  True  True]
[ True  True False False]


In [14]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [19]:
a = np.triu(np.ones((3,3)), 1)
print(a)
print(a.T)

[[ 0.  1.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  1.  0.]]


In [21]:
help(np.triu)

Help on function triu in module numpy.lib.twodim_base:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of a matrix with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [25]:
# broadcasting
a = np.tile(np.arange(0,40,10), (3,1)).T
print(a)
b = np.array([0,1,2])
print(a+b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [40]:
a = np.array([[1,2,3], [4,5,6]])
print(a, a.ravel(), a.T.ravel())
print(a.shape)
a = a.reshape(3,2)
print(a)


[[1 2 3]
 [4 5 6]] [1 2 3 4 5 6] [1 4 2 5 3 6]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [45]:
z = np.array([1,2,3])
print(z)
z, z[:, np.newaxis], z[np.newaxis, :]

[1 2 3]


(array([1, 2, 3]), array([[1],
        [2],
        [3]]), array([[1, 2, 3]]))

In [47]:
a = np.arange(4*3*2).reshape(4,3,2)
print(a.shape, a)


(4, 3, 2) [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [55]:
a = np.array([[4,3,5], [1,2,1]])
print(np.sort(a, axis=1))
print(np.sort(a, axis=0))
a.sort(axis=1)
print(a)
a = np.array([4,3,1,2])
print(np.argsort(a))


[[3 4 5]
 [1 1 2]]
[[1 2 1]
 [4 3 5]]
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
