# ハイパーパラメータ自動調整いろいろ
## Kerasと遺伝アルゴリズム

https://qiita.com/cvusk/items/1f3b178f34c39beb29ff#_reference-3c5df6e5237c0c705690

https://github.com/shibuiwilliam/keras_opt/blob/master/ga_nn.ipynb


In [3]:
import numpy as np
import pandas as pd
import random

from keras.layers import Activation, Dropout, BatchNormalization, Dense
from keras.models import Sequential
from keras.datasets import mnist
from keras.metrics import categorical_crossentropy
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping

In [36]:
class MNIST():
    def __init__(self, 
                 l1_out=512, l2_out=512, 
                 l1_drop=0.2, l2_drop=0.2,
                 bn1=0, bn2=0,
                 batch_size=100, epochs=10,
                 validation_split=0.1):
        self.l1_out = l1_out
        self.l2_out = l2_out
        self.l1_drop = l1_drop
        self.l2_drop = l2_drop
        self.bn1 = bn1
        self.bn2 = bn2
        self.batch_size = batch_size
        self.epochs = epochs
        self.validation_split = validation_split
        self.__x_train, self.__xtest, self.__y_train, self.__y_test = self.mnist_data()
        self.__model = self.mnist_model()
        params = """
        validation_split:\t{0}
        l1_drop:\t{1}
        l2_drop:\t{2}
        l1_out:\t{3}
        l2_out:\t{4}
        bn1:\t{5}
        bn2:\t{6}
        batch_size:\t{7}
        epochs:\t{8}
        """.format(self.validation_split,
                   self.l1_drop, self.l2_drop,
                   self.l1_out, self.l2_out,
                   self.bn1, self.bn2,
                   self.batch_size, self.epochs)
        print(params)
        
    def mnist_data(self):
        """load mnist data from keras dataset
        """
        (X_train, y_train), (X_test, y_test) = mnist.load_data()
        
        X_train = X_train.reshape(60000, 784)
        X_test = X_test.reshape(10000, 784)
        X_train /= 255
        X_test /= 255
        X_train = X_train.astype('float32')
        X_test = X_test.astype('float32')
        Y_train = np_utils.to_categorical(y_train, 10)
        Y_test = np_utils.to_categorical(y_test, 10)
        
        return X_train, X_test, Y_train, Y_test
    
    def mnist_model(self):
        model = Sequential()
        model.add(Dense(self.l1_out, input_shape=(784,)))
        if self.bn1 == 0:
            model.add(BatchNormalization())
        model.add(Activation('relu'))
        model.add(Dropout(self.l1_drop))
        
        model.add(Dense(self.l2_out))
        if self.bn2 == 0:
            model.add(BatchNormalization())
        model.add(Activation('relu'))
        model.add(Dropout(self.l2_drop))
        
        model.add(Dense(10))
        model.add(Activation('softmax'))
        model.compile(loss='categorical_crossentropy',
                     optimizer=Adam(),
                     metrics=['accuracy'])
        
        return model
    
    def mnist_fit(self):
        early_stopping = EarlyStopping(patience=0, verbose=1)
        
        self.__model.fit(self.__x_train, self.__y_train,
                        batch_size=self.batch_size,
                        epochs=self.epochs,
                        verbose=0,
                        validation_split=self.validation_split,
                        callbacks=[early_stopping])
        
    def mnist_evaluate(self):
        self.mnist_fit()
        
        evaluation = self.__model.evaluate(self.__x_test,
                                          self.__y_test,
                                          batch_size,
                                          verbose=0)
        return evaluation
    
   

In [31]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
print("X_train", X_train.shape, X_train[0, :6, :6])
print("y_train", y_train.shape, y_train[:6])

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
print(X_train.shape)
print(X_train[0, :6])

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
print(X_train.shape)
print(X_train[0, :6])

X_train /= 255
X_test /= 255
print(X_train.shape)
print(X_train[0, :6])


X_train (60000, 28, 28) [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
y_train (60000,) [5 0 4 1 9 2]
(60000, 784)
[0 0 0 0 0 0]
(60000, 784)
[0. 0. 0. 0. 0. 0.]
(60000, 784)
[0. 0. 0. 0. 0. 0.]


In [33]:
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

print("y_train", type(y_train), y_train.shape, y_train[0])

print("Y_train", type(Y_train), Y_train.shape, Y_train[0])


y_train <class 'numpy.ndarray'> (60000,) 5
Y_train <class 'numpy.ndarray'> (60000, 10) [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [38]:
def run_mnist(bounds):
    _mnist = MNIST(l1_out=bounds[0], 
                   l2_out=bounds[1], 
                   l1_drop=bounds[2], 
                   l2_drop=bounds[3], 
                   bn1=bounds[4],
                   bn2=bounds[5],
                   batch_size=bounds[6],
                   epochs=bounds[7], 
                   validation_split=bounds[8])
    mnist_evaluation = _mnist.mnist_evaluate()
    print(mnist_evaluation)
    return mnist_evaluation[0],

In [39]:
from deap import base, creator, tools, algorithms

C:\Users\alanc\Anaconda3\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)


In [40]:
creator.create('FitnessMax', base.Fitness, weights = (-1.0, ))
creator.create('Individual', list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register('l1_out', random.choice, (64, 128, 256, 512, 1024))
toolbox.register('l2_out', random.choice, (64, 128, 256, 512, 1024))
toolbox.register("l1_drop", random.uniform, 0.0, 0.3)
toolbox.register("l2_drop", random.uniform, 0.0, 0.3)
toolbox.register("bn1", random.randint, 0, 1)
toolbox.register("bn2", random.randint, 0, 1)
toolbox.register("batch_size", random.choice, (10, 100, 500))
toolbox.register("epochs", random.choice, (5, 10, 20))
toolbox.register("validation_split", random.uniform, 0.0, 0.3)


