# ハイパーパラメータ自動調整いろいろ
## Kerasと遺伝アルゴリズム

https://qiita.com/cvusk/items/1f3b178f34c39beb29ff#_reference-3c5df6e5237c0c705690

https://github.com/shibuiwilliam/keras_opt/blob/master/ga_nn.ipynb


In [1]:
import numpy as np
import pandas as pd
import random

from keras.layers import Activation, Dropout, BatchNormalization, Dense
from keras.models import Sequential
from keras.datasets import mnist
from keras.metrics import categorical_crossentropy
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping

C:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# MNIST class
class MNIST():
    def __init__(self,
                 l1_out=512, 
                 l2_out=512, 
                 l1_drop=0.2, 
                 l2_drop=0.2, 
                 bn1=0,
                 bn2=0,
                 batch_size=100, 
                 epochs=10, 
                 validation_split=0.1):
        self.l1_out = l1_out
        self.l2_out = l2_out
        self.l1_drop = l1_drop
        self.l2_drop = l2_drop
        self.bn1 = bn1
        self.bn2 = bn2
        self.batch_size = batch_size
        self.epochs = epochs
        self.validation_split = validation_split
        self.__x_train, self.__x_test, self.__y_train, self.__y_test = self.mnist_data()
        self.__model = self.mnist_model()
        params = """
        l1_out:\t{0}
        l2_out:\t{1}
        l1_drop:\t{2}
        l2_drop:\t{3}
        bn1:\t{4}
        bn2:\t{5}
        batch_size:\t{6}
        epochs:\t{7}
        validation_split:\t{8}
        """.format(self.l1_out, self.l2_out,
                   self.l1_drop, self.l2_drop,
                   self.bn1, self.bn2,
                   self.batch_size, self.epochs,
                   self.validation_split)
        print(params)
        
    # load mnist data from keras dataset
    def mnist_data(self):
        (X_train, y_train), (X_test, y_test) = mnist.load_data()
        X_train = X_train.reshape(60000, 784)
        X_test = X_test.reshape(10000, 784)

        X_train = X_train.astype('float32')
        X_test = X_test.astype('float32')
        X_train /= 255
        X_test /= 255

        Y_train = np_utils.to_categorical(y_train, 10)
        Y_test = np_utils.to_categorical(y_test, 10)
        return X_train, X_test, Y_train, Y_test
    
    # mnist model
    def mnist_model(self):
        model = Sequential()
        model.add(Dense(self.l1_out, input_shape=(784,)))
        if self.bn1 == 0:
            model.add(BatchNormalization())
        model.add(Activation('relu'))
        model.add(Dropout(self.l1_drop))
        model.add(Dense(self.l2_out))
        if self.bn2 == 0:
            model.add(BatchNormalization())
        model.add(Activation('relu'))
        model.add(Dropout(self.l2_drop))
        model.add(Dense(10))
        model.add(Activation('softmax'))
        model.compile(loss='categorical_crossentropy',
                      optimizer=Adam(),
                      metrics=['accuracy'])

        return model
    
    # fit mnist model
    def mnist_fit(self):
        early_stopping = EarlyStopping(patience=0, verbose=1)
        
        self.__model.fit(self.__x_train, self.__y_train,
                       batch_size=self.batch_size,
                       epochs=self.epochs,
                       verbose=0,
                       validation_split=self.validation_split,
                       callbacks=[early_stopping])
    
    # evaluate mnist model
    def mnist_evaluate(self):
        self.mnist_fit()
        
        evaluation = self.__model.evaluate(self.__x_test, self.__y_test, batch_size=self.batch_size, verbose=0)
        return evaluation

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
print("X_train", X_train.shape, X_train[0, :6, :6])
print("y_train", y_train.shape, y_train[:6])

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
print(X_train.shape)
print(X_train[0, :6])

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
print(X_train.shape)
print(X_train[0, :6])

X_train /= 255
X_test /= 255
print(X_train.shape)
print(X_train[0, :6])


X_train (60000, 28, 28) [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
y_train (60000,) [5 0 4 1 9 2]
(60000, 784)
[0 0 0 0 0 0]
(60000, 784)
[0. 0. 0. 0. 0. 0.]
(60000, 784)
[0. 0. 0. 0. 0. 0.]


In [4]:
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

print("y_train", type(y_train), y_train.shape, y_train[0])

print("Y_train", type(Y_train), Y_train.shape, Y_train[0])


y_train <class 'numpy.ndarray'> (60000,) 5
Y_train <class 'numpy.ndarray'> (60000, 10) [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [5]:
def run_mnist(bounds):
    _mnist = MNIST(l1_out=bounds[0], 
                   l2_out=bounds[1], 
                   l1_drop=bounds[2], 
                   l2_drop=bounds[3], 
                   bn1=bounds[4],
                   bn2=bounds[5],
                   batch_size=bounds[6],
                   epochs=bounds[7], 
                   validation_split=bounds[8])
    mnist_evaluation = _mnist.mnist_evaluate()
    print(mnist_evaluation)
    return mnist_evaluation[0],

In [6]:
from deap import base, creator, tools, algorithms

C:\Program Files\Anaconda3\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)


In [12]:
creator.create('FitnessMax', base.Fitness, weights = (-1.0, ))
creator.create('Individual', list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register('L1_out', random.choice, (64, 128, 256, 512, 1024))
toolbox.register('L2_out', random.choice, (64, 128, 256, 512, 1024))
toolbox.register("L1_drop", random.uniform, 0.0, 0.3)
toolbox.register("L2_drop", random.uniform, 0.0, 0.3)
toolbox.register("bn1", random.randint, 0, 1)
toolbox.register("bn2", random.randint, 0, 1)
toolbox.register("batch_size", random.choice, (10, 100, 500))
toolbox.register("epochs", random.choice, (5, 10, 20))
toolbox.register("validation_split", random.uniform, 0.0, 0.3)

toolbox.register('individual', tools.initCycle, creator.Individual,
                 (toolbox.L1_out, toolbox.L2_out,
                 toolbox.L1_drop, toolbox.L2_drop,
                 toolbox.bn1, toolbox.bn2,
                 toolbox.batch_size, toolbox.epochs, toolbox.validation_split),
                 n=1)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("evaluate", run_mnist)


C:\Program Files\Anaconda3\lib\site-packages\deap\creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
C:\Program Files\Anaconda3\lib\site-packages\deap\creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)


In [13]:
def genAlg(population=5, CXPB=0.5, MUTPB=0.2, NGEN=5):
    """Function for running hyper parameter optimization on Genetic Algorithm"""
    random.seed(64)
    pop = toolbox.population(n=population)
    
    print("Start of evolution")
    
    fitnesses = list(map(toolbox.evaluate, pop))
    for ind, fit in zip(pop, fitnesses):
        ind.fitness.values = fit
        
    print("  Evaluated %i individuals" % len(pop))
    
    for g in range(NGEN):
        print("-- Generation %i --" % g)
        
        offspring = toolbox.select(pop, len(pop))
        offspring = list(map(toolbox.clone, offspring))
        
        for child1, child2 in zip(offspring[::2], offspring[1::2]):
            if random.random() < CXPB:
                print("mate")
                toolbox.mate(child1, child2)
                del child1.fitness.values
                del child2.fitness.values
                
        for mutant in offspring:
            if random.random() < MUTPB:
                print("mutate")
                toolbox.mutate(mutant)
                del mutant.fitness.values
        try:
            invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
            fitness = map(toolbox.evaluate, invalid_ind)
            for ind, fit in zip(invalid_ind, fitnesses):
                ind.fitness.values = fit
        except AssertionError:
            pass
        
        pop[:] = offspring
        
        try:
            fits = [ind.fitness.values[0] for ind in pop]
            
            length = len(pop)
            mean = sum(fits)/length
            sum2 = sum(x*x for x in fits)
            std = abs(sum2/length - mean**2)**0.5

            print("    Min %s" % min(fits))
            print("    Max %s" % max(fits))
            print("    Avg %s" % mean)
            print("    Std %s" % std)
        except IndexError:
            pass
    print("-- End of (successful) evolution --")
    
    best_ind = tools.selBest(pop, 1)[0]
    print("Best individual is %s, %s" % (best_ind, best_ind.fitness.values))
    return best_ind


best_int = genAlg(population=5, CXPB=0.5, MUTPB=0.2, NGEN=10)

Start of evolution

        l1_out:	512
        l2_out:	64
        l1_drop:	0.18906571629566554
        l2_drop:	0.12118829087054188
        bn1:	0
        bn2:	0
        batch_size:	100
        epochs:	20
        validation_split:	0.27380697683392835
        
Epoch 00007: early stopping
[0.07106867912851157, 0.9772000056505203]

        l1_out:	128
        l2_out:	128
        l1_drop:	0.023943619120116687
        l2_drop:	0.12502013021715647
        bn1:	0
        bn2:	0
        batch_size:	10
        epochs:	10
        validation_split:	0.20383943374115368
        
[0.06667245912841327, 0.9809999964833259]

        l1_out:	64
        l2_out:	64
        l1_drop:	0.052369065073309795
        l2_drop:	0.17600891153302792
        bn1:	1
        bn2:	0
        batch_size:	500
        epochs:	5
        validation_split:	0.026646503392500687
        
[0.11047704452648759, 0.9665000021457673]

        l1_out:	64
        l2_out:	512
        l1_drop:	0.11910387551405677
        l2_drop:	0.0641

In [14]:
print(best_int)

[128, 128, 0.023943619120116687, 0.12502013021715647, 0, 0, 10, 10, 0.20383943374115368]
