https://deap.readthedocs.io/en/master/tutorials/advanced/numpy.html

In [1]:
import numpy
from deap import base, creator
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", numpy.ndarray, fitness=creator.FitnessMax)

In [2]:
a = [1,2,3,4]
b = [5,6,7,8]
print(a[1:3], b[1:3])
a[1:3], b[1:3] = b[1:3], a[1:3]
print(a)
print(b)
# listの場合, swapは普通にできる

[2, 3] [6, 7]
[1, 6, 7, 4]
[5, 2, 3, 8]


In [4]:
import numpy
a = numpy.array([1,2,3,4])
b = numpy.array([5,6,7,8])
print(a[1:3], b[1:3])
a[1:3], b[1:3] = b[1:3], a[1:3]
print(a)
print(b)
# numpyの場合、swap済みのaからのa[1:3]を代入してしまうため、b[1:3]が新しいaの部分になってしまう

[2 3] [6 7]
[1 6 7 4]
[5 6 7 8]


In [6]:
import numpy
a = numpy.array([1,2,3,4])
b = numpy.array([5,6,7,8])
print(a[1:3], b[1:3])
a[1:3], b[1:3] = b[1:3].copy(), a[1:3].copy()
print(a)
print(b)

[2 3] [6 7]
[1 6 7 4]
[5 2 3 8]


In [9]:
import operator

a = numpy.array([1,2,3])
b = numpy.array([1,2,3])
operator.eq(a,b)

array([ True,  True,  True], dtype=bool)

In [12]:
a == b

array([ True,  True,  True], dtype=bool)

In [13]:
if operator.eq(a,b):
    print("Gosh!")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
from deap import tools
hof = tools.HallOfFame(1, similar=numpy.array_equal)


In [16]:
if numpy.array_equal(a,b):
    print("Yeah!")

Yeah!


In [17]:
numpy.array_equal(a,b)

True