https://keras.io/ja/getting-started/sequential-model-guide/    

# 多層パーセプトロン (MLP) を用いた多値分類:

In [1]:
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

import numpy as np

/home/yuki/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
X_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(
    np.random.randint(10, size=(1000, 1)), num_classes=10)
X_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(
    np.random.randint(10, size=(100, 1)), num_classes=10)

y_train[:10]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [3]:
model = Sequential()

model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
             optimizer=sgd,
             metrics=['accuracy'])
model.fit(X_train, y_train,
         epochs=20,
         batch_size=128)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/20
1000/1000 [==============================] - 1s 526us/step - loss: 2.4081 - acc: 0.1000
Epoch 2/20
1000/1000 [==============================] - 0s 77us/step - loss: 2.4038 - acc: 0.0830
Epoch 3/20
1000/1000 [==============================] - 0s 79us/step - loss: 2.3459 - acc: 0.1120
Epoch 4/20
1000/1000 [==============================] - 0s 87us/step - loss: 2.3172 - acc: 0.1220
Epoch 5/20
1000/1000 [==============================] - 0s 80us/step - loss: 2.3267 - acc: 0.1010
Epoch 6/20
1000/1000 [==============================] - 0s 71us/step - loss: 2.3085 - acc: 0.1050
Epoch 7/20
1000/1000 [==============================] - 0s 64us/step - loss: 2.3090 - acc: 0.1060
Epoch 8/20
1000/1000 [==============================] - 0s 63us/step - loss: 2.3085 - acc: 0.1110
Epoch 9/20
1000/1000 [==============================] - 0s 84us/step - loss: 2.3044 - acc: 0.1190
Epoch 10/20
1000/1000 [==============================] - 0s 74us/step - loss: 2.3066 - acc: 0.1180
Epoch 11/20
1000/1

In [4]:
score

[2.3013827800750732, 0.14000000059604645]

In [5]:
from keras.utils import plot_model

# summarize layers
print(model.summary())
# plot graph
plot_model(model, to_file='model.png')


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                1344      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 6,154
Trainable params: 6,154
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
from ann_visualizer.visualize import ann_viz
ann_viz(model, title="My first NN")

# MLPを用いた二値分類:

In [19]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [21]:
X_train = np.random.random((1000, 20))
y_train = np.random.randint(2, size=(1000, 1))
X_test = np.random.random((100, 20))
y_test = np.random.randint(2, size=(100, 1))

y_train[:10]

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [22]:
model = Sequential()
model.add(Dense(64, input_dim=20, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss="binary_crossentropy",
             optimizer='rmsprop',
             metrics=['accuracy'])

model.fit(X_train, y_train,
         epochs=20,
         batch_size=128)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/20
1000/1000 [==============================] - 0s 145us/step - loss: 0.7094 - acc: 0.5150
Epoch 2/20
1000/1000 [==============================] - 0s 12us/step - loss: 0.7016 - acc: 0.5000
Epoch 3/20
1000/1000 [==============================] - 0s 13us/step - loss: 0.7024 - acc: 0.5030
Epoch 4/20
1000/1000 [==============================] - 0s 14us/step - loss: 0.7083 - acc: 0.4970
Epoch 5/20
1000/1000 [==============================] - 0s 12us/step - loss: 0.6991 - acc: 0.5180
Epoch 6/20
1000/1000 [==============================] - 0s 12us/step - loss: 0.6927 - acc: 0.5280
Epoch 7/20
1000/1000 [==============================] - 0s 13us/step - loss: 0.6952 - acc: 0.5050
Epoch 8/20
1000/1000 [==============================] - 0s 13us/step - loss: 0.7005 - acc: 0.4990
Epoch 9/20
1000/1000 [==============================] - 0s 13us/step - loss: 0.6963 - acc: 0.5270
Epoch 10/20
1000/1000 [==============================] - 0s 12us/step - loss: 0.6961 - acc: 0.5100
Epoch 11/20
1000/1

In [23]:
score

[0.6852235198020935, 0.550000011920929]

In [24]:
from keras.utils import plot_model

# summarize layers
print(model.summary())
# plot graph
plot_model(model, to_file='model.png')


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 64)                1344      
_________________________________________________________________
dropout_8 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 64)                4160      
_________________________________________________________________
dropout_9 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 65        
Total params: 5,569
Trainable params: 5,569
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
from mlxtend.plotting import plot_learning_curves

plot_learning_curves(X_train, y_train, X_test, y_test, model, scoring='accuracy')
plt.show()

Epoch 1/1
100/100 [==============================] - 0s 100us/step - loss: 0.6797 - acc: 0.6000


ValueError: Classification metrics can't handle a mix of binary and continuous targets

# VGG-likeなconvnet

In [11]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD

In [12]:
X_train = np.random.random((100, 100, 100, 3))
y_train = keras.utils.to_categorical(
    np.random.randint(10, size=(100, 1)),
    num_classes=10
)
y_train[:10]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [13]:
X_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(
    np.random.randint(10, size=(20, 1)),
    num_classes=10
)

In [14]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu',
                 input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(X_train, y_train, batch_size=32, epochs=10)
score = model.evaluate(X_test, y_test, batch_size=32)
score

Epoch 1/10
100/100 [==============================] - 3s 31ms/step - loss: 2.3075
Epoch 2/10
100/100 [==============================] - 3s 27ms/step - loss: 2.3427
Epoch 3/10
100/100 [==============================] - 3s 26ms/step - loss: 2.2785
Epoch 4/10
100/100 [==============================] - 3s 27ms/step - loss: 2.2772
Epoch 5/10
100/100 [==============================] - 3s 27ms/step - loss: 2.2877
Epoch 6/10
100/100 [==============================] - 3s 29ms/step - loss: 2.2531
Epoch 7/10
100/100 [==============================] - 3s 33ms/step - loss: 2.2842
Epoch 8/10
100/100 [==============================] - 3s 32ms/step - loss: 2.3201
Epoch 9/10
100/100 [==============================] - 3s 33ms/step - loss: 2.2697
Epoch 10/10
20/20 [==============================] - 0s 10ms/step


2.3302948474884033

In [15]:
from keras.utils import plot_model

# summarize layers
print(model.summary())
# plot graph
plot_model(model, to_file='model.png')


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 98, 98, 32)        896       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 96, 96, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 46, 46, 64)        18496     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 44, 44, 64)        36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 22, 22, 64)        0         
__________

# LSTMを用いた系列データ分類:

データがないから試せられない。max_features変数は下記URLを参照

https://github.com/keras-team/keras/issues/5394

# 手書き文字の認識(1): 全結合層のみ
https://qiita.com/yampy/items/706d44417c433e68db0d

In [ ]:
from keras.datasets import mnist

# 内容は10種類の数字の白黒画像(28x28)です。
# 訓練データが60000枚、テストデータが10000枚となっております。
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.shape

In [ ]:
x_train[0].shape