https://keras.io/ja/getting-started/sequential-model-guide/    

# 多層パーセプトロン (MLP) を用いた多値分類:

In [10]:
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

import numpy as np

In [35]:
X_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(
    np.random.randint(10, size=(1000, 1)), num_classes=10)
X_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(
    np.random.randint(10, size=(100, 1)), num_classes=10)

y_train[:10]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

In [36]:
model = Sequential()

model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
             optimizer=sgd,
             metrics=['accuracy'])
model.fit(X_train, y_train,
         epochs=20,
         batch_size=128)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/20
1000/1000 [==============================] - 1s 586us/step - loss: 2.3735 - acc: 0.1130
Epoch 2/20
1000/1000 [==============================] - 0s 73us/step - loss: 2.3685 - acc: 0.1060
Epoch 3/20
1000/1000 [==============================] - 0s 89us/step - loss: 2.3227 - acc: 0.1050
Epoch 4/20
1000/1000 [==============================] - 0s 79us/step - loss: 2.3226 - acc: 0.1020
Epoch 5/20
1000/1000 [==============================] - 0s 72us/step - loss: 2.3185 - acc: 0.1000
Epoch 6/20
1000/1000 [==============================] - 0s 64us/step - loss: 2.3204 - acc: 0.1040
Epoch 7/20
1000/1000 [==============================] - 0s 61us/step - loss: 2.3162 - acc: 0.0850
Epoch 8/20
1000/1000 [==============================] - 0s 64us/step - loss: 2.3132 - acc: 0.0920
Epoch 9/20
1000/1000 [==============================] - 0s 80us/step - loss: 2.3087 - acc: 0.0990
Epoch 10/20
1000/1000 [==============================] - 0s 69us/step - loss: 2.2965 - acc: 0.1130
Epoch 11/20
1000/1

In [37]:
score

[2.307941198348999, 0.11999999731779099]

# MLPを用いた二値分類:

In [26]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [29]:
X_train = np.random.random((1000, 20))
y_train = np.random.randint(2, size=(1000, 1))
X_test = np.random.random((100, 20))
y_test = np.random.randint(2, size=(100, 1))

y_train[:10]

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [31]:
model = Sequential()
model.add(Dense(64, input_dim=20, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss="binary_crossentropy",
             optimizer='rmsprop',
             metrics=['accuracy'])

model.fit(X_train, y_train,
         epochs=20,
         batch_size=128)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/20
1000/1000 [==============================] - 0s 469us/step - loss: 0.7363 - acc: 0.5040
Epoch 2/20
1000/1000 [==============================] - 0s 54us/step - loss: 0.7115 - acc: 0.4990
Epoch 3/20
1000/1000 [==============================] - 0s 61us/step - loss: 0.7135 - acc: 0.5250
Epoch 4/20
1000/1000 [==============================] - 0s 54us/step - loss: 0.7015 - acc: 0.5120
Epoch 5/20
1000/1000 [==============================] - 0s 51us/step - loss: 0.7049 - acc: 0.5140
Epoch 6/20
1000/1000 [==============================] - 0s 65us/step - loss: 0.7001 - acc: 0.5230
Epoch 7/20
1000/1000 [==============================] - 0s 73us/step - loss: 0.6988 - acc: 0.5190
Epoch 8/20
1000/1000 [==============================] - 0s 63us/step - loss: 0.7015 - acc: 0.5170
Epoch 9/20
1000/1000 [==============================] - 0s 68us/step - loss: 0.6984 - acc: 0.5260
Epoch 10/20
1000/1000 [==============================] - 0s 74us/step - loss: 0.6929 - acc: 0.5150
Epoch 11/20
1000/1

In [33]:
score

[0.6891276836395264, 0.5400000214576721]

# VGG-likeなconvnet

In [39]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD

In [42]:
X_train = np.random.random((100, 100, 100, 3))
y_train = keras.utils.to_categorical(
    np.random.randint(10, size=(100, 1)),
    num_classes=10
)
y_train[:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [45]:
X_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(
    np.random.randint(10, size=(20, 1)),
    num_classes=10
)

In [47]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu',
                 input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(X_train, y_train, batch_size=32, epochs=10)
score = model.evaluate(X_test, y_test, batch_size=32)
score

Epoch 1/10
100/100 [==============================] - 14s 140ms/step - loss: 2.3306
Epoch 2/10
100/100 [==============================] - 13s 134ms/step - loss: 2.3756
Epoch 3/10
100/100 [==============================] - 19s 185ms/step - loss: 2.2935
Epoch 4/10
100/100 [==============================] - 17s 171ms/step - loss: 2.2941
Epoch 5/10
100/100 [==============================] - 19s 193ms/step - loss: 2.2981
Epoch 6/10
100/100 [==============================] - 16s 162ms/step - loss: 2.2893
Epoch 7/10
100/100 [==============================] - 15s 146ms/step - loss: 2.2886
Epoch 8/10
100/100 [==============================] - 17s 171ms/step - loss: 2.2873
Epoch 9/10
100/100 [==============================] - 15s 149ms/step - loss: 2.2622
Epoch 10/10
20/20 [==============================] - 1s 51ms/step


2.32685923576355

# LSTMを用いた系列データ分類:

データがないから試せられない。max_features変数は下記URLを参照

https://github.com/keras-team/keras/issues/5394

# 手書き文字の認識(1): 全結合層のみ
https://qiita.com/yampy/items/706d44417c433e68db0d

In [59]:
from keras.datasets import mnist

# 内容は10種類の数字の白黒画像(28x28)です。
# 訓練データが60000枚、テストデータが10000枚となっております。
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.shape

(60000, 28, 28)

In [58]:
x_train[0].shape

(28, 28)