In [1]:
import numpy as np

In [2]:
a = np.array([[0,1,2], [3,4,5], [6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
a[1]

array([3, 4, 5])

In [4]:
a[1, 2]

5

In [6]:
a[1,2] = 1000
a

array([[   0,    1,    2],
       [   3,    4, 1000],
       [   6,    7,    8]])

In [8]:
a[-2, -2]

4

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[1:8:2]

array([1, 3, 5, 7])

In [12]:
a[0:8:3]

array([0, 3, 6])

In [17]:
a[-1:-10:-2]

array([9, 7, 5, 3, 1])

In [20]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
a[:, 3] = 100
a

array([[  0,   1,   2, 100,   4],
       [  5,   6,   7, 100,   9],
       [ 10,  11,  12, 100,  14],
       [ 15,  16,  17, 100,  19],
       [ 20,  21,  22, 100,  24]])

In [25]:
a[:2, :3]=10000
a

array([[10000, 10000, 10000,   100,     4],
       [10000, 10000, 10000,   100,     9],
       [   10,    11,    12,   100,    14],
       [   15,    16,    17,   100,    19],
       [   20,    21,    22,   100,    24]])

In [27]:
a[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [28]:
a = np.arange(15, 0, -1)
a

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [29]:
a[[1,5,6,2]]

array([14, 10,  9, 13])

In [31]:
n = a > 5
n

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [32]:
a[a>5]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6])

In [35]:
a[a%2==0]

array([14, 12, 10,  8,  6,  4,  2])

In [38]:
a[(4<a) & (a>10)]

array([15, 14, 13, 12, 11])

In [39]:
True & False

False

In [40]:
True and False

False

In [42]:
a[a<10] = 10
a

array([15, 14, 13, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [44]:
a = np.tile(np.arange(3), 3)
a

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [45]:
np.argmax(a)

2

In [46]:
np.argmin(a)

0

In [47]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.nonzero(a)

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [50]:
np.nonzero([0, 1, 2, 3,4,5,5])

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [51]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
np.where(a%2==0)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 4, 1, 3, 0, 2, 4], dtype=int64))

In [53]:
a = np.arange(10)
np.select([a <3, a>5], [a, a**2])

array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81])

In [54]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
b = np.arange(8, -1, -1).reshape((3,3))
b

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [58]:
np.dstack((a,b))

array([[[0, 8],
        [1, 7],
        [2, 6]],

       [[3, 5],
        [4, 4],
        [5, 3]],

       [[6, 2],
        [7, 1],
        [8, 0]]])

In [59]:
a = np.random.randint(0, 100, 10)
a

array([70, 45, 97, 33, 89, 88, 64, 58, 55, 36])

In [61]:
a.sort()
a

array([33, 36, 45, 55, 58, 64, 70, 88, 89, 97])

In [62]:
a = np.arange(1, 10, 1).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a = np.array([[1,4,2], [9,6,8], [5,3,7]])
a


array([[1, 4, 2],
       [9, 6, 8],
       [5, 3, 7]])

In [64]:
np.sort(a)

array([[1, 2, 4],
       [6, 8, 9],
       [3, 5, 7]])

In [66]:
a

array([[1, 4, 2],
       [9, 6, 8],
       [5, 3, 7]])

In [67]:
np.sort(a, axis=0)

array([[1, 3, 2],
       [5, 4, 7],
       [9, 6, 8]])

In [68]:
a

array([[1, 4, 2],
       [9, 6, 8],
       [5, 3, 7]])

In [69]:
np.sort(a, axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a

array([[1, 4, 2],
       [9, 6, 8],
       [5, 3, 7]])

In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a, b


(array([1, 2, 3]), array([4, 5, 6]))

In [72]:
a+b

array([5, 7, 9])

In [73]:
np.add(a,b)

array([5, 7, 9])